"""empty message

Revision ID: 3ea433e7a98c
Revises: ac6545354f66
Create Date: 2022-10-06 18:40:39.004946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ea433e7a98c'
down_revision = 'ac6545354f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planets', 'population',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'planets', ['planet_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.alter_column('planets', 'population',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
