"""empty message

Revision ID: 6922b3996510
Revises: ac6545354f66
Create Date: 2022-10-06 16:55:57.183341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6922b3996510'
down_revision = 'ac6545354f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('height', sa.String(length=50), nullable=True))
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'characters', ['character_name'])
    op.drop_column('characters', 'heigth')
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planets', 'population',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'planets', ['planet_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.alter_column('planets', 'population',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.add_column('characters', sa.Column('heigth', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'characters', type_='unique')
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('characters', 'height')
    # ### end Alembic commands ###
